### PR TITLE
SLING-9906 : Avoid retrying to load jobs if classes are missing

### PR DESCRIPTION
**Pull request by stefan-egli**

### CODE REVIEW

**Comment by stefan-egli** [comment]
Not sure why there are these build errors, it's complaining about
```
Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.ops4j.pax.logging:pax-logging-api:jar:1.8.4
```

**Review by cziegeler — APPROVED** [review]
Lgtm, thanks

**Review by cziegeler — APPROVED** [review]
Lgtm, thanks!

**Comment by stefan-egli** [comment]
Following output from jenkins (sort of looks unrelated to my changes ... ) :
```
+ mvn -U clean verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=apache -Dsonar.projectKey=apache_sling-org-apache-sling-event -Pjacoco-report -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-merged/jacoco.xml -Dsonar.pullrequest.branch=SLING-9906 -Dsonar.pullrequest.base=master -Dsonar.pullrequest.key=8 -Pci
----- withMaven Wrapper script -----
Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/home/jenkins/workspace/ling-org-apache-sling-event_PR-8@tmp/withMaven319b0e24/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/home/jenkins/workspace/ling-org-apache-sling-event_PR-8@tmp/withMaven319b0e24" 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/jenkins/tools/maven/latest3
Java version: 11.0.9, vendor: Oracle Corporation, runtime: /usr/local/asfpackages/java/oraclejdk-11.0.9
Default locale: en_US, platform encoding: ISO-8859-1
OS name: "linux", version: "4.15.0-76-generic", arch: "amd64", family: "unix"
[INFO] [jenkins-event-spy] Generate /home/jenkins/workspace/ling-org-apache-sling-event_PR-8@tmp/withMaven319b0e24/maven-spy-20210201-180903-12312722978851857616059.log.tmp ...
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.apache.sling:org.apache.sling.event:bundle:4.2.13-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.mockito:mockito-all:jar -> version 1.10.19 vs 1.9.5 @ line 382, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
[INFO] Downloading from Nexus: http://repository.apache.org/snapshots/org/apache/maven/plugins/maven-metadata.xml
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
[INFO] Downloading from Nexus: http://repository.apache.org/snapshots/org/codehaus/mojo/maven-metadata.xml
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 kB at 34 kB/s)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 23 kB/s)
[INFO] Downloaded from Nexus: http://repository.apache.org/snapshots/org/apache/maven/plugins/maven-metadata.xml (8.5 kB at 12 kB/s)
[INFO] Downloading from Nexus: http://repository.apache.org/snapshots/org/codehaus/mojo/sonar-maven-plugin/maven-metadata.xml
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/sonar-maven-plugin/maven-metadata.xml
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/sonar-maven-plugin/maven-metadata.xml (1.2 kB at 43 kB/s)
[INFO] 
[INFO] --------------< org.apache.sling:org.apache.sling.event >---------------
[INFO] Building Apache Sling Event Support 4.2.13-SNAPSHOT
[INFO] -------------------------------[ bundle ]-------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ org.apache.sling.event ---
[INFO] Deleting /home/jenkins/workspace/ling-org-apache-sling-event_PR-8/target
[INFO] Deleting /home/jenkins/workspace/ling-org-apache-sling-event_PR-8 (includes = [derby.log], excludes = [])
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-property-values) @ org.apache.sling.event ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-java) @ org.apache.sling.event ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (ban-maven-scr-plugin) @ org.apache.sling.event ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (prepare-agent) @ org.apache.sling.event ---
[INFO] argLine set to -javaagent:/home/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/jenkins/workspace/ling-org-apache-sling-event_PR-8/target/jacoco-unit.exec
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (process-resource-bundles) @ org.apache.sling.event ---
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ org.apache.sling.event ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ org.apache.sling.event ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 3 resources
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ org.apache.sling.event ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 58 source files to /home/jenkins/workspace/ling-org-apache-sling-event_PR-8/target/classes
[INFO] /home/jenkins/workspace/ling-org-apache-sling-event_PR-8/src/main/java/org/apache/sling/event/impl/jobs/scheduling/JobSchedulerImpl.java: Some input files use unchecked or unsafe operations.
[INFO] /home/jenkins/workspace/ling-org-apache-sling-event_PR-8/src/main/java/org/apache/sling/event/impl/jobs/scheduling/JobSchedulerImpl.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-bundle-plugin:3.5.0:manifest (scr-metadata) @ org.apache.sling.event ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ org.apache.sling.event ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/jenkins/workspace/ling-org-apache-sling-event_PR-8/src/test/resources
[INFO] Copying 3 resources
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ org.apache.sling.event ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 30 source files to /home/jenkins/workspace/ling-org-apache-sling-event_PR-8/target/test-classes
[INFO] /home/jenkins/workspace/ling-org-apache-sling-event_PR-8/src/test/java/org/apache/sling/event/it/AbstractJobHandlingTest.java: /home/jenkins/workspace/ling-org-apache-sling-event_PR-8/src/test/java/org/apache/sling/event/it/AbstractJobHandlingTest.java uses or overrides a deprecated API.
[INFO] /home/jenkins/workspace/ling-org-apache-sling-event_PR-8/src/test/java/org/apache/sling/event/it/AbstractJobHandlingTest.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/jenkins/workspace/ling-org-apache-sling-event_PR-8/src/test/java/org/apache/sling/event/impl/jobs/jmx/QueuesMBeanImplTest.java: Some input files use unchecked or unsafe operations.
[INFO] /home/jenkins/workspace/ling-org-apache-sling-event_PR-8/src/test/java/org/apache/sling/event/impl/jobs/jmx/QueuesMBeanImplTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ org.apache.sling.event ---
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Skipping Apache Sling Event Support
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.617 s
[INFO] Finished at: 2021-02-01T18:09:21Z
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "ci" could not be activated because it does not exist.
[INFO] [jenkins-event-spy] Generated /home/jenkins/workspace/ling-org-apache-sling-event_PR-8@tmp/withMaven319b0e24/maven-spy-20210201-180903-12312722978851857616059.log
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project org.apache.sling.event: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test failed. NullPointerException -> [Help 1]
```

**Comment by stefan-egli** [comment]
I'm assuming the jenkins errors are unrelated to this PR - https://github.com/apache/sling-org-apache-sling-event/pull/8/commits/752055ed7d0641bc44e9ba60c78481dc7a778f01 helped indeed - so will merge anyway.

**Pull request merged**
