### PR TITLE
SLING-5767

### PR DESCRIPTION
**Pull request by mahsumdemir**
Include the Illegal Argument Exception message in the logsAdd exception detail to message

### CODE REVIEW

**Comment by rombert** [comment]
A SonarQube report for the changes added _only by this pull request_ was generated. Please review it at https://builds.apache.org/job/Sling/job/sling-org-apache-sling-event/job/PR-3/3/artifact/target/sonar/issues-report/issues-report-light.html

**Comment by mahsumdemir** [comment]
Updated the PR according to SonarQube report

**Comment by rombert** [comment]
A SonarQube report for the changes added _only by this pull request_ was generated. Please review it at https://builds.apache.org/job/Sling/job/sling-org-apache-sling-event/job/PR-3/4/artifact/target/sonar/issues-report/issues-report-light.html

**Comment by rombert** [comment]
@cziegeler , @eglistefan - any thoughts on this?

**Comment by cziegeler** [comment]
I agree that the exception message might be useful, however there is no guarantee that the exception message contains the illegal topic. Therefore I would at least always log the topic even if that means its logged twice.

**Comment by eglistefan** [comment]
I do agree with Carsten that the topic should be included.

Additionally I'd like to better understand the gain of the patch. From what I can see the IllegalArgumentException comes from osgi's `Event.validateTopicName()` and I fail to see more details in the log message than the fact that it's invalid.

Not saying logging the exception might not be useful, but I'd like to understand what case this patch likes to improve. @mahsumdemir wdyt?

**Comment by mahsumdemir** [comment]
Well, I found the issue while going over a list of issues which are good for newcomers to OSS and then implemented it according to the code written to the issue. So my motivation for the PR was a contribution to OSS :).

I also looked at OSGI's Event.validateTopicName method while implementing it and this additional logging did not make much sense to me too.

**Comment by eglistefan** [comment]
> I found the issue while going over a list of issues .. and then implemented it according to the code written to the issue

Great initiative! Much appreciated!

> I also looked at OSGI's Event.validateTopicName method while implementing it and this additional logging did not make much sense to me too.

Same here. I'm inclinded to suggest keeping it as is. Or then as Carsten suggested to re-include the topic at least.

**Comment by mahsumdemir** [comment]
I will go with keeping it as is.

**Pull request closed without merging**
